version: "3.5"
services:
  database:
    image: mongo:4.0.4
    networks:
      - app-network
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
  service-auth:
    image: agranom/service-auth
    build:
      context: ./service-auth
      dockerfile: ./devops/docker/Dockerfile
    networks:
      - app-network
    env_file:
      - ./service-auth/devops/config/local.env
    ports:
      - "3001:3001"
    restart: on-failure
  service-task:
    image: agranom/service-task
    build:
      context: ./service-task
      dockerfile: ./devops/docker/Dockerfile
    networks:
      - app-network
    env_file:
      - ./service-task/devops/config/local.env
    ports:
      - "3000:3000"
    restart: on-failure
  web-app:
    image: agranom/todo-web-app
    build:
      context: ./web-app
      dockerfile: ./devops/docker/Dockerfile
      args:
        - ENVIRONMENT=dev
    ports:
      - "8000:80"
    networks:
      - app-network


volumes:
  mongodb:
  mongodb_config:
networks:
  app-network:
    driver: bridge
